name: simulacrum-space
services:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: krummja/simulacrum-space
  name: simulacrum-space